<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="urn:ecommerceservicewsdl"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    targetNamespace="urn:ecommerceservicewsdl">

    <types>
        <xsd:schema targetNamespace="urn:ecommercewsdl">
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
            <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
        </xsd:schema>
    </types>

<!--
	<message name="newRequest">
		<part name="nom" type="xsd:string"/>
		<part name="email" type="xsd:string"/>
		<part name="sujet" type="xsd:string"/>
		<part name="message" type="xsd:string"/>
		<part name="created" type="xsd:datetime"/>
		<part name="modified" type="xsd:datetime"/>
		<part name="public" type="xsd:boolean"/>
		<part name="lu" type="xsd:boolean"/>
    </message>

    <message name="newResponse">
        <part name="return" type="xsd:string"/>
    </message>
-->

    <portType name="ecommercewsdlPortType">

       <!--
		<operation name="new">
            <documentation>ajouter un contact</documentation>
            <input message="tns:newRequest"/>
            <output message="tns:newResponse"/>
        </operation>
		-->
    </portType>

    <binding name="ecommercewsdlBinding" type="tns:ecommercewsdlPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>



       <!--
		<operation name="new">
            <soap:operation soapAction="urn:arnleadservicewsdl#new" style="rpc"/>

            <input>
                <soap:body use="encoded" namespace="urn:ecommercewsdl"
                    encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>

            <output>
                <soap:body use="encoded" namespace="urn:ecommercewsdl"
                    encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
		-->
    </binding>

    <service name="ecommercewsdl">
        <port name="ecommercewsdlPort" binding="tns:ecommercewsdlBinding">
            <soap:address location="http://127.0.0.1:8000/soap"/>
        </port>
    </service>
</definitions>